FROM golang:1.17 AS build-env

ENV CGO_ENABLED=0
ENV PORT 4040

ARG DB_HOST
ARG DB_PORT
ARG DB_NAME
ARG DB_USER
ARG DB_PASSWORD

ENV DB_HOST=$DB_HOST
ENV DB_PORT=$DB_PORT
ENV DB_NAME=$DB_NAME
ENV DB_USER=$DB_NAME
ENV DB_PASSWORD=$DB_PASSWORD

WORKDIR /app
COPY . .

RUN go mod download
RUN go mod verify
RUN go build -o gordle ./cmd/srv/

FROM alpine

WORKDIR /

COPY --from=build-env /app/gordle .

EXPOSE $PORT

CMD ["./gordle"]
