name: Build and push Docker images

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  dockerhub:
    runs-on: ubuntu-latest
    environment: gordle-build

    steps:
      - name: checkout sources
        uses: actions/checkout@v2.3.4

      - name: Set up docker builders
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v1.14.1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push server image
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: patrikolin/gordle:latest
          file: Dockerfile.srv

      - name: Build and push daily image
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: patrikolin/gordle-daily:latest
          file: Dockerfile.daily
          build-args: |
            DB_HOST=${{ env.DB_HOST }}
            DB_PORT=${{ env.DB_PORT }}
            DB_NAME=${{ env.DB_NAME }}
            DB_USER=${{ env.DB_USER }}
            DB_PASSWORD=${{ env.DB_PASSWORD }}
